version: "3.7"
services: 
    db:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: prisciladd
        volumes: 
            - ./api/db/data:/var/lib/mysql
        restart: always

    web:
        build:
            "./api"
        container_name: web-container
        restart: always
        volumes: 
            - ./api
        ports: 
            - "9001:9001"
        depends_on: 
            - db
